### ISSUE TITLE
Fix code scanning alert - Workflow does not contain permissions

### ISSUE THREAD

**Issue by Apoll011** [Apoll011/Avi-core#4]
# GitHub Workflow Missing Permissions

## Issue Description

The GitHub workflow `.github/workflows/test.yml` has been flagged for not containing explicit permissions, which is a security best practice. Workflows without defined permissions use legacy default settings that may be overly permissive.

## Current Workflow

```yaml
# .github/workflows/test.yml:13
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt,clippy
      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Build (release)
        run: cargo build --release --verbose
      - name: Run Clippy
        run: cargo clippy --verbose -- 
      - name: Check formatting
        run: cargo fmt -- --check
```

## Recommendation

Add a `permissions` block to the workflow to explicitly define the required access levels. For a basic build/test workflow like this, minimal permissions are typically sufficient.

### Suggested Fix

```yaml
name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Set permissions to minimum required
permissions:
  contents: read
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt,clippy
      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Build (release)
        run: cargo build --release --verbose
      - name: Run Clippy
        run: cargo clippy --verbose -- 
      - name: Check formatting
        run: cargo fmt -- --check
```

## Why This Matters

- **Security**: Workflows without explicit permissions default to broad access rights
- **Best Practice**: GitHub recommends setting the minimum required permissions
- **Security Alerts**: This helps resolve security alerts in the repository
- **Principle of Least Privilege**: Actions should only have access to what they absolutely need

## Additional Resources

- [[GitHub Docs: Workflow permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token)](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token)
- [[GitHub Security Best Practices](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions)](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions)
